openapi: 3.0.0
info:
  title: anuto
  version: '1.0'
  description: API for Anuto TD
  contact:
    name: Cartesi
    url: https://www.cartesi.io
    email: info@cartesi.io
  license:
    name: Apache 2.0
    url: 'https://github.com/cartesi-corp/anuto-server/blob/develop/LICENSE'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Tournament
  - name: Tournament Score
paths:
  /tournaments:
    get:
      summary: List of Tournaments
      description: Gets a paginated list of all tournaments, which can be filtered using query parameters
      operationId: getTournaments
      tags:
        - Tournament
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: integer
                  limit:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: ./models/tournament.v1.yaml
              examples:
                example-1:
                  value:
                    $ref: './examples/tournaments.json'
      parameters:
        - in: query
          name: limit
          description: Maximum number of tournaments to return (default applies if not specified)
          schema:
            type: integer
        - in: query
          name: offset
          description: Pagination offset, 10 returns 10th element up to (10+limit)th element
          schema:
            type: integer
        - in: query
          name: phase
          description: Filter tournaments by phase
          schema:
            type: string
            enum:
              - commit
              - reveal
              - round
              - end
        - in: query
          name: me
          description: Filter tournaments which I am participating
          schema:
            type: boolean
        - in: query
          name: sort_by
          description: Sort criteria of returned tournaments
          schema:
            type: string
            enum:
              - playerCount
              - deadline
        - in: query
          name: order_by
          description: Ascendent or descendent order of returned tournaments. Default is asc.
          schema:
            type: string
            enum:
              - asc
              - desc
  /tournaments/{id}:
    parameters:
      - in: path
        name: id
        description: Id of the tournament
        schema:
          type: string
        required: true
    get:
      summary: Tournament
      description: Gets a tournament definition and its current status
      operationId: getTournamentById
      tags:
        - Tournament
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/tournament.v1.yaml
              examples:
                commit:
                  summary: Tournament in commit phase
                  value:
                    $ref: ./examples/tournament_commit.json
                reveal:
                  summary: Tournament in reveal phase
                  value:
                    $ref: ./examples/tournament_reveal.json
                round:
                  summary: Tournament in round phase
                  value:
                    $ref: ./examples/tournament_round.json
                end:
                  summary: Tournament in end phase
                  value:
                    $ref: ./examples/tournament_end.json
        '404':
          description: Not Found
  /tournaments/{tournament_id}/scores/{id}:
    parameters:
      - in: path
        name: tournament_id
        description: Id of the tournament
        required: true
        schema:
          type: string
      - in: path
        name: id
        description: Id of the score in the tournament
        required: true
        schema:
          type: string
    get:
      summary: Score
      description: Retrieve specific score of a player in a tournament
      operationId: getTournamentScoreById
      tags:
        - Tournament Score
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/score.v1.yaml
              examples:
                p1:
                  value:
                    id: "1"
                    score: 3981
                p2:
                  value:
                    id: "2"
                    score: 5039
                p3:
                  value:
                    id: "3"
                    score: 30291
                p4:
                  value:
                    id: "4"
                    score: 2353

        '403':
          description: Forbidden
        '404':
          description: Not Found
  /tournaments/{tournament_id}/scores/my:
    parameters:
      - in: path
        name: tournament_id
        description: Id of the tournament
        required: true
        schema:
          type: string
    get:
      summary: My Score
      description: Retrieve my score of the tournament
      operationId: getMyTournamentScore
      tags:
        - Tournament Score
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/score.v1.yaml
              example:
                - id: "1"
                  score: 3981
                  log:
                    actions:
                    - type: add_turret
                      tick: 0
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 2
                    - type: next_wave
                      tick: 0
                    - type: add_turret
                      tick: 46
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 7
                    - type: add_turret
                      tick: 81
                      typeTurret: laser
                      position:
                        r: 3
                        c: 6
                    - type: next_wave
                      tick: 114
                    - type: add_turret
                      tick: 312
                      typeTurret: launch
                      position:
                        r: 6
                        c: 2
                    - type: next_wave
                      tick: 312
                    - type: next_wave
                      tick: 665
                    - type: next_wave
                      tick: 1687
                    - type: add_turret
                      tick: 2547
                      typeTurret: glue
                      position:
                        r: 6
                        c: 4
                    - type: next_wave
                      tick: 2779
        '404':
          description: Not Found
    put:
      summary: Update My Score
      description: Send my score to the tournament
      operationId: updateMyTournamentScore
      tags:
        - Tournament Score
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/score.v1.yaml
              example:
                - id: "1"
                  score: 3981
                  log:
                    actions:
                    - type: add_turret
                      tick: 0
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 2
                    - type: next_wave
                      tick: 0
                    - type: add_turret
                      tick: 46
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 7
                    - type: add_turret
                      tick: 81
                      typeTurret: laser
                      position:
                        r: 3
                        c: 6
                    - type: next_wave
                      tick: 114
                    - type: add_turret
                      tick: 312
                      typeTurret: launch
                      position:
                        r: 6
                        c: 2
                    - type: next_wave
                      tick: 312
                    - type: next_wave
                      tick: 665
                    - type: next_wave
                      tick: 1687
                    - type: add_turret
                      tick: 2547
                      typeTurret: glue
                      position:
                        r: 6
                        c: 4
                    - type: next_wave
                      tick: 2779
        '403':
          description: 'Forbidden, tournament is not accepting gameplays'
        '404':
          description: Not Found
        '409':
          description: 'Conflict, you already have a better score'
      requestBody:
        description: The result of my gameplay
        content:
          application/json:
            schema:
              type: object
              properties:
                score:
                  type: integer
                  description: My score
                log:
                  $ref: ./models/log.v1.yaml
              required:
                - score
                - log
            example:
                - score: 3981
                  log:
                    actions:
                    - type: add_turret
                      tick: 0
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 2
                    - type: next_wave
                      tick: 0
                    - type: add_turret
                      tick: 46
                      typeTurret: projectile
                      position:
                        r: 3
                        c: 7
                    - type: add_turret
                      tick: 81
                      typeTurret: laser
                      position:
                        r: 3
                        c: 6
                    - type: next_wave
                      tick: 114
                    - type: add_turret
                      tick: 312
                      typeTurret: launch
                      position:
                        r: 6
                        c: 2
                    - type: next_wave
                      tick: 312
                    - type: next_wave
                      tick: 665
                    - type: next_wave
                      tick: 1687
                    - type: add_turret
                      tick: 2547
                      typeTurret: glue
                      position:
                        r: 6
                        c: 4
                    - type: next_wave
                      tick: 2779
components:
  schemas: {}
